language: cpp

compiler:  
    - gcc

# Install dependencies
addons:
  apt:
    packages:
      - doxygen
      - doxygen-doc
      - doxygen-latex
      - doxygen-gui
      - graphviz
    
before_script:  
    - mkdir build
    - cd build
    - cmake ..

script: 
    - make
    - test/testAvlTree
 
deploy:
  local_dir: doc_doxygen/html
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  on:
    branch: master